# version of node to use
FROM node:20 

# Directory to save image
WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure that the both package lock are copies
COPY  package*.json ./
RUN npm install

# COPY all files to /app
COPY . .
EXPOSE 3000
CMD [ "npm", "run", "start" ]